### ISSUE TITLE
Not sure what those error log meaning?

### ISSUE THREAD

**Issue by CoolLKKPS** [qwbarch/mirage#100]
@qwbarch 
![1730216782926](https://github.com/user-attachments/assets/1275533a-1c01-4a1e-8b21-344df6198123)

**Comment by CoolLKKPS** [comment]
from my friend modpack (not create by me)

**Comment by qwbarch** [comment]
Should be fixed for the next update

**Comment by qwbarch** [comment]
Closing this as it should be fixed. If it still occurs, please re-open the issue
