### ISSUE TITLE
Mimics Turn invisible and lose collision (but still makes sounds) when the player they visually copy dies

### ISSUE THREAD

**Issue by Epic001YT** [qwbarch/mirage#101]
This was tested without other mods to make sure other mods were not conflicting in any way.

If a mimic spawns and copies visuals/speech from player A, and player A then dies (Either by player B killing them or other causes) the mimic then goes invisible and cannot kill player B any more, however it still copies speech and can be seen from spectators, just not people that are alive.

**Comment by qwbarch** [comment]
Thanks for the report. Do you mind uploading some logs? Does this issue happen every time a player dies after they're mimicked?

**Comment by qwbarch** [comment]
Closing this issue as there hasn't been a response in awhile. Feel free to re-open if you're here.
