### ISSUE TITLE
our whole party hasnt gotten any mimicked voices or masked spawns since the big v60 update. Currently running Mirage v1.11.1

### ISSUE THREAD

**Issue by elliot430** [qwbarch/mirage#104]
Our mod pack code is 01930014-af60-f3bf-688f-22b993ef53c7. What else can I provide to help troubleshoot, where should i start looking?

**Comment by qwbarch** [comment]
Sorry for the late response. Can you provide a full log? I'm assuming there should be errors if nobody is able to hear any voices

**Comment by qwbarch** [comment]
Are you maybe getting errors similar to #105?

**Comment by qwbarch** [comment]
Can you try seeing if [MirageExperimental v0.0.44](<https://thunderstore.io/c/lethal-company/p/qwbarch/MirageExperimental/>) works for you?

**Comment by elliot430** [comment]
![image](https://github.com/user-attachments/assets/f1bfab06-0adf-4645-a46b-f5436f25e889)
i'm getting this error


[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Component.CompareTag (System.String tag) (at <e27997765c1848b09d8073e5d642717a>:IL_0001)
(wrapper dynamic-method) EnemyAI.DMD<EnemyAI::EnableEnemyMesh>(EnemyAI,bool,bool)
StartOfRound.SetPlayerSafeInShip () (at <d491ed1d4cc34874a2498af41192fe04>:IL_006B)
AudioReverbTrigger.ChangeAudioReverbForPlayer (GameNetcodeStuff.PlayerControllerB pScript) (at <d491ed1d4cc34874a2498af41192fe04>:IL_01AB)
AudioReverbTrigger.OnTriggerStay (UnityEngine.Collider other) (at <d491ed1d4cc34874a2498af41192fe04>:IL_018B)

[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Component.CompareTag (System.String tag) (at <e27997765c1848b09d8073e5d642717a>:IL_0001)
(wrapper dynamic-method) EnemyAI.DMD<EnemyAI::EnableEnemyMesh>(EnemyAI,bool,bool)
StartOfRound.SetPlayerSafeInShip () (at <d491ed1d4cc34874a2498af41192fe04>:IL_006B)
AudioReverbTrigger.ChangeAudioReverbForPlayer (GameNetcodeStuff.PlayerControllerB pScript) (at <d491ed1d4cc34874a2498af41192fe04>:IL_01AB)
AudioReverbTrigger.OnTriggerStay (UnityEngine.Collider other) (at <d491ed1d4cc34874a2498af41192fe04>:IL_018B)

[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Component.CompareTag (System.String tag) (at <e27997765c1848b09d8073e5d642717a>:IL_0001)
(wrapper dynamic-method) EnemyAI.DMD<EnemyAI::EnableEnemyMesh>(EnemyAI,bool,bool)
StartOfRound.SetPlayerSafeInShip () (at <d491ed1d4cc34874a2498af41192fe04>:IL_006B)
AudioReverbTrigger.ChangeAudioReverbForPlayer (GameNetcodeStuff.PlayerControllerB pScript) (at <d491ed1d4cc34874a2498af41192fe04>:IL_01AB)
AudioReverbTrigger.OnTriggerStay (UnityEngine.Collider other) (at <d491ed1d4cc34874a2498af41192fe04>:IL_018B)

[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Component.CompareTag (System.String tag) (at <e27997765c1848b09d8073e5d642717a>:IL_0001)
(wrapper dynamic-method) EnemyAI.DMD<EnemyAI::EnableEnemyMesh>(EnemyAI,bool,bool)
StartOfRound.SetPlayerSafeInShip () (at <d491ed1d4cc34874a2498af41192fe04>:IL_006B)
AudioReverbTrigger.ChangeAudioReverbForPlayer (GameNetcodeStuff.PlayerControllerB pScript) (at <d491ed1d4cc34874a2498af41192fe04>:IL_01AB)
AudioReverbTrigger.OnTriggerStay (UnityEngine.Collider other) (at <d491ed1d4cc34874a2498af41192fe04>:IL_018B)

[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Component.CompareTag (System.String tag) (at <e27997765c1848b09d8073e5d642717a>:IL_0001)
(wrapper dynamic-method) EnemyAI.DMD<EnemyAI::EnableEnemyMesh>(EnemyAI,bool,bool)
StartOfRound.SetPlayerSafeInShip () (at <d491ed1d4cc34874a2498af41192fe04>:IL_006B)
AudioReverbTrigger.ChangeAudioReverbForPlayer (GameNetcodeStuff.PlayerControllerB pScript) (at <d491ed1d4cc34874a2498af41192fe04>:IL_01AB)
AudioReverbTrigger.OnTriggerStay (UnityEngine.Collider other) (at <d491ed1d4cc34874a2498af41192fe04>:IL_018B)

[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Component.CompareTag (System.String tag) (at <e27997765c1848b09d8073e5d642717a>:IL_0001)
(wrapper dynamic-method) EnemyAI.DMD<EnemyAI::EnableEnemyMesh>(EnemyAI,bool,bool)
StartOfRound.SetPlayerSafeInShip () (at <d491ed1d4cc34874a2498af41192fe04>:IL_006B)
AudioReverbTrigger.ChangeAudioReverbForPlayer (GameNetcodeStuff.PlayerControllerB pScript) (at <d491ed1d4cc34874a2498af41192fe04>:IL_01AB)
AudioReverbTrigger.OnTriggerStay (UnityEngine.Collider other) (at <d491ed1d4cc34874a2498af41192fe04>:IL_018B)

[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Component.CompareTag (System.String tag) (at <e27997765c1848b09d8073e5d642717a>:IL_0001)
(wrapper dynamic-method) EnemyAI.DMD<EnemyAI::EnableEnemyMesh>(EnemyAI,bool,bool)
StartOfRound.SetPlayerSafeInShip () (at <d491ed1d4cc34874a2498af41192fe04>:IL_006B)
AudioReverbTrigger.ChangeAudioReverbForPlayer (GameNetcodeStuff.PlayerControllerB pScript) (at <d491ed1d4cc34874a2498af41192fe04>:IL_01AB)
AudioReverbTrigger.OnTriggerStay (UnityEngine.Collider other) (at <d491ed1d4cc34874a2498af41192fe04>:IL_018B)

[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Component.CompareTag (System.String tag) (at <e27997765c1848b09d8073e5d642717a>:IL_0001)
(wrapper dynamic-method) EnemyAI.DMD<EnemyAI::EnableEnemyMesh>(EnemyAI,bool,bool)
StartOfRound.SetPlayerSafeInShip () (at <d491ed1d4cc34874a2498af41192fe04>:IL_006B)
AudioReverbTrigger.ChangeAudioReverbForPlayer (GameNetcodeStuff.PlayerControllerB pScript) (at <d491ed1d4cc34874a2498af41192fe04>:IL_01AB)
AudioReverbTrigger.OnTriggerStay (UnityEngine.Collider other) (at <d491ed1d4cc34874a2498af41192fe04>:IL_018B)

[Info   : Unity Log] Despawning props and enemies #2
[Info   : Unity Log] Despawning props and enemies #3
[Info   : Unity Log] Enemies on map: 6
[Info   : Unity Log] despawn enemies on map
[Info   : Unity Log] despawn enemies on map
[Info   : Unity Log] despawn enemies on map
[Info   : Unity Log] despawn enemies on map
[Info   : Unity Log] despawn enemies on map
[Info   : Unity Log] despawn enemies on map
[Info   : Unity Log] despawn nest spawn object
[Warning: Unity Log] Can not play a disabled audio source
[Error  : Unity Log] NullReferenceException
Stack trace:
Mirage.Domain.Audio.Receiver.onReceiveFrame (Mirage.Domain.Audio.Receiver+AudioReceiver receiver, Mirage.Domain.Audio.Frame+FrameData frameData) (at ./Mirage/Domain/Audio/Receiver.fs:61)
Mirage.Unity.AudioStream+onFrameRead@69.Invoke (Mirage.Domain.Audio.Frame+FrameData frameData) (at ./Mirage/Unity/AudioStream.fs:70)
Mirage.Domain.Audio.Sender+consumer@58-3.Invoke (Microsoft.FSharp.Core.FSharpOption`1[T] frameData) (at ./Mirage/Domain/Audio/Sender.fs:62)
Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b] (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt, b result1, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] userCode) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:528)
Microsoft.FSharp.Control.Trampoline.Execute (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] firstAction) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:112)
--- End of stack trace from previous location where exception was thrown ---
<StartupCode$FSharp-Core>.$Async+StartImmediate@1794-1.Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo edi) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:1794)
Microsoft.FSharp.Control.AsyncPrimitives+StartWithContinuations@1185-2.Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo x) (at <8b3b61bb207b2ce2fc6552fadafedf72>:IL_0000)
Microsoft.FSharp.Control.Trampoline.Execute (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] firstAction) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:138)
<StartupCode$FSharp-Core>.$Async+clo@178-14.Invoke (System.Object o) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:181)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <e27997765c1848b09d8073e5d642717a>:IL_0002)
UnityEngine.UnitySynchronizationContext.Exec () (at <e27997765c1848b09d8073e5d642717a>:IL_005D)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <e27997765c1848b09d8073e5d642717a>:IL_0014)

**Comment by qwbarch** [comment]
From what it looks like the ``NullReferenceException`` appears to be from when enemies despawn, so this *should* be harmless. The other errors are unrelated to Mirage.
Is everything else working alright? Or are voices not playing back at all still?

**Comment by qwbarch** [comment]
Do you mind posting a full log as well actually? Would make it a bit easier for me to debug

**Comment by elliot430** [comment]
Where do i go to get the full log?

Also are the logs still accessible even though it was a session from yesterday? Not sure when the next time we'll play is.

Thanks,
________________________________

**Comment by qwbarch** [comment]
Yes the log are still accessible from your previous session. If you're on r2modman, go to ``Settings`` and search up ``log``, and then click on ``Copy log file contents to clipboard`` and paste it here

**Comment by qwbarch** [comment]
This issue should be fixed in ``Mirage v1.12.0``. If you're still not able to hear any mimicked voices, feel free to re-open the issue.
