### ISSUE TITLE
Masked always mimics the host.

### ISSUE THREAD

**Issue by rabbit-time** [qwbarch/mirage#109]
If there's only one Masked, it will always mimic the host and no other player, making it very redundant at times. 

Ideally, it should choose a player at random every time a Masked spawns. A config option to enable random player choice would be appreciated.

**Comment by qwbarch** [comment]
Sorry I missed this issue. How many masked have you run into? If your sample size is small, this is probably RNG being RNG.
It's already set to select a random player, although it avoids picking the same player after it's already been picked, until all players have been picked.

**Comment by rabbit-time** [comment]
I've played with the mod a good bit and have run into dozens of instances, so I don't think it's RNG.

**Comment by qwbarch** [comment]
I can confirm this is not the case so I'll be closing the issue. I've restarted the game a couple times to spawn a masked, and it sometimes mimics the non-host as I'd expect
