### ISSUE TITLE
problem with sounds

### ISSUE THREAD

**Issue by Tikhworks** [qwbarch/mirage#115]
hello i have a problem, mimics don't play sounds 
[LogOutput.log](https://github.com/user-attachments/files/18137645/LogOutput.log)

**Comment by qwbarch** [comment]
Thanks for the logs. It seems like there's no errors coming from Mirage.  
Can you check if your Lethal Company folder for the ``Mirage/Recording`` folder, and see if it contains and ``.opus`` files?

**Comment by qwbarch** [comment]
Closing this issue as there hasn't been a response. Feel free to re-open the issue if you're here.
