### ISSUE TITLE
feature: AEIOUcompany support (replay tts, maybe chat too)

### ISSUE THREAD

**Issue by soupcantrolling** [qwbarch/mirage#41]
AEIOUcompany allows every text message to play from the player with moonbase alpha's tts
since i cant talk, this is a replacement for me having a mic. my friends can hear themselves and i can also hear them, but i cant be mimicked because i do not use the mic. would be cool if it could play me back, maybe add chat if the enemy is close enough too..

**Comment by qwbarch** [comment]
I don't remember if I mentioned this on discord, but while I do plan on having this as a feature, it'll take awhile before I get to this part since I'm focusing on v2's [features](https://discord.com/channels/1168655651455639582/1200695291972685926/1210038530160599060) for now

**Comment by qwbarch** [comment]
Closing this issue as I don't have time to work on new features
