### ISSUE TITLE
The CW version of this mod is missing a monster.

### ISSUE THREAD

**Issue by TinyDerp** [qwbarch/mirage#61]
Like I said in the title the Content Warning version is missing a monster (or more). The monster that I found to be missing in the config is the [Angler](https://www.rockpapershotgun.com/content-warning-monsters#Angler) and literally the only mob (maybe idk) that is designed to lure you in by giving you a false sense of security. Please consider adding this monster to the config.

**Comment by qwbarch** [comment]
While I can add it, doesn't the Angler already do voice mimicking by itself?

**Comment by TinyDerp** [comment]
To my knowledge it dosn't, well atleast I have never heard it mimic voices. I also wane clarify that the option should be added to the anglers mimic (oc _if_ it's a separate entety) not to the angler itslef, though the option can still be there.

**Comment by qwbarch** [comment]
Gotcha. I'm a bit busy right now so I'll try tp get to this sometime this week

**Comment by qwbarch** [comment]
Release is out, sorry for the late update
