### ISSUE TITLE
[1.7.0] Enemy and Environmental SFX Spam at High Volume instead of Recorded Player Audio; All Player Audio Breaks

### ISSUE THREAD

**Issue by Silhygames** [qwbarch/mirage#64]
We were using Mirage during our stream last night and we experienced a bug several times where the host suddenly started hearing constant enemy noises (vanilla and modded SFX; not player voices) seemingly over the player channel at extremely high volumes. Leaving the planet would cause the sounds to be replaced by extremely loud engine SFX from the ship, instead.

During this time, no other player can be heard, making it a fairly critical error. It could only be stopped by completely closing the game and restarting.

When the issue starts, the console shows Mirage spontaneously and indefinitely spawning errors such as the following: https://pastebin.com/9WYQuFtY

I also have several clips of the event, including one that shows the console with Mirage throwing the error: https://pastebin.com/LPwiPYn5

**Comment by qwbarch** [comment]
The common error in that log is ``Win32 IO returned 112``, which apparently means the user's disk is full. Is the host low on storage space?

**Comment by Silhygames** [comment]
You know, that is a possibility. The game files are installed on my Z: Drive, which is my high-speed 1TB Sabrent Rocket NVMe. I use it for most of my high-end and modded games for its incredibly high read and write speeds.

I think I usually have a decent cushion of space on it, but with mods, logs, and the audio clips being generated real-time, it's very possible it exceeded that at some point.

I'll clear out some space and do some testing to see if I can confirm the cause.

**Comment by qwbarch** [comment]
Sounds good, let me know. I've never heard of this issue before and the logs spam that error a lot, so it's likely the culprit

**Comment by Silhygames** [comment]
We spent a few hours with the mod just now, and it didn't seem to reoccur, so I think you nailed it.

I would never have guessed that once it ran out of space for clips it just threw SFX at us, ha. Glad to have gotten that one sorted out.

**Comment by qwbarch** [comment]
Unexpected errors sure does lead to weird behaviour sometimes. Glad it's fixed!
