### ISSUE TITLE
Mirage - does not copy the voices of some players.

### ISSUE THREAD

**Issue by Dedenne030** [qwbarch/mirage#70]
** There may be mistranslation using the translator. 
I'm sorry for the inaccurate translation.

This mode does not copy the voices of some players. 
(I don't know if this is relevant, but if the player is a woman)

I've been playing for nearly 100 hours but I can't hear the voice imitating. 
The voice of a non-female player sounds normal.

How can I solve this problem?

**Comment by qwbarch** [comment]
Is this for Lethal Company or Content Warning?

If it's for Content Warning, I'm afraid I have no time to look into the issue.  
If it's for Lethal Company, does the user have windows username that contains non-ascii characters? (E.g. accented characters)
I've had a report that it's currently bugged for that, and is something I'll have to look into sometime.

**Comment by Dedenne030** [comment]
Thank you for your answer.
It's the Lethal Company.

I used a Korean windows username. 
Does it have nothing to do with the Steam nickname? 
I recently changed to an English Steam nickname and had the same problem.
I'll change the Windows nickname, too.

**Comment by qwbarch** [comment]
Could you try using an english windows nickname and confirm if that fixes it for you? If it does, I'll definitely have to fix it sometime when I'm able to

**Comment by Dedenne030** [comment]
I changed my Windows nickname to English today and played the game. Still can't hear my voice.
I wonder what the problem is.

**Comment by qwbarch** [comment]
Do you mind uploading your logs?

**Comment by Dedenne030** [comment]
Here you go. Please let me know if you need anything else.

[LOG.txt](https://github.com/user-attachments/files/15830546/LOG.txt)
[LOG.txt](https://github.com/user-attachments/files/15830546/LOG.txt)

**Comment by Dedenne030** [comment]
I'm sorry.
I only changed the Windows user name,
The user file name on 'C: folder' hasn't changed. I'll change that folder as well and try playing it again.

**Comment by qwbarch** [comment]
Ah sounds good, let me know how that goes!

**Comment by Dedenne030** [comment]
It's been resolved. Thank you.
Are you planning to support the non-ascii code by any chance?

**Comment by qwbarch** [comment]
Thanks for confirming. I'll likely look into it sometime next week, since I'm a bit busy figuring out other things right now

**Comment by qwbarch** [comment]
Started looking into it now actually. I've found the library that's causing this issue and have reported it to the library author, but it may take time before I get a response back from them

**Comment by qwbarch** [comment]
Fixed in the latest update

**Comment by Dedenne030** [comment]
Thank you for your help.

**Comment by qwbarch** [comment]
Glad it's working well for you now!
