### ISSUE TITLE
[CW] Only record the host's voice?

### ISSUE THREAD

**Issue by Lusiiky** [qwbarch/mirage#73]
Hello,

I have the impression that my voice is recorded everywhere when I play with my friends, but never their voice... why? Is this normal? Is there a problem?

Thanks!

**Comment by qwbarch** [comment]
Seems like one of the updates (either the game itself or MyceliumNetworking) broke Mirage. I don't have time to look into this for the moment unfortunately, so I'll have to fix it later down the line

**Comment by qwbarch** [comment]
No time to support the content warning mod, closing this issue
