### ISSUE TITLE
Mirage causes monsters to no longer spawn

### ISSUE THREAD

**Issue by ResistVR** [qwbarch/mirage#74]
Mirage causes monsters to no longer spawn, help?

**Comment by qwbarch** [comment]
Is this for Lethal Company or Content Warning? If it's for LC, I'll probably have to update it sometime

**Comment by HisBoilingPoint** [comment]
Lethal Company. I can confirm after much pain that this mod does cause issues. They only seem to spawn inside at like 7:30ish so I assume it's related to the spawn curve.

**Comment by qwbarch** [comment]
> Lethal Company. I can confirm after much pain that this mod does cause issues. They only seem to spawn inside at like 7:30ish so I assume it's related to the spawn curve.

You can turn off the custom spawn curve in the config by setting ``UseCustomSpawnCurve`` to ``false``

**Comment by qwbarch** [comment]
The patch that changes the spawn curve only runs if ``enableOverrideSpawnChance`` is set to ``true``, so if there's still an issue even with it set to ``false``, I'm afraid there's nothing I can do on my end

**Comment by qwbarch** [comment]
Closing this as it's not really an issue as far as I'm aware
