### ISSUE TITLE
My friends cannot hear me after the ship lands on a moon

### ISSUE THREAD

**Issue by Bluerith** [qwbarch/mirage#75]
This issue seems to be originating from this mod, I am unsure of what exactly is causing it, but everything works fine until we land on a moon, then the people I'm playing with lose the ability to hear me. Aside from that, it appears to be working perfectly. 

Really fun mod btw!

**Comment by qwbarch** [comment]
Mirage has been stable for quite a long time now. I highly doubt this issue comes from this mod, otherwise I would've received a lot of bug reports regarding this issue by now.

If you're able to pinpoint the issue more and it *is* confirmed from Mirage, I'd be happy to look into it some more

**Comment by Bluerith** [comment]
At least, playing with a modpack featuring: More Company, Late Company, and Too Many Emotes, this issue presents itself only when Mirage is enabled and it disappears when the mod is disabled. 

I can do some further testing and maybe try a clean install of Lethal Company. I am the only one of my friend group (7 people) that is having the issue. Will let you know if I discover the cause of the issue!

**Comment by qwbarch** [comment]
Could you send me your logs if it happens again actually? I can't promise I'll be able to figure out the issue, but I could at least take a quick look

**Comment by Bluerith** [comment]
So, I ended up reinstalling it to my PC's hard drive, it must have been an issue with permissions since it works perfectly now, thanks a ton for your time!

**Comment by qwbarch** [comment]
Glad it's working for you now!
