### ISSUE TITLE
InvalidProgramException

### ISSUE THREAD

**Issue by SheriffSans** [qwbarch/mirage#79]
The mod does not work in the game, in the console this error:
![Screenshot_1](https://github.com/user-attachments/assets/2b0225fd-0399-45a4-9439-0677d9b8a746)

**Comment by qwbarch** [comment]
Is ``ApplyPenalty`` set to ``false``? If it is, try leaving it as ``true``, since that option shouldn't really be used anymore. If it's already set to ``true``, then I'm not sure what the issue is, but either way I'll probably just remove the option on the next update

**Comment by Rebootly** [comment]
I found the reason why the mod is not working. It's all about the ConfigurableCompany. For some reason, it conflicts with this mod. It is not surprising that the others also report the bug, but in other cases of this mod. So removing this mod solves the problem.

**Comment by SheriffSans** [comment]
Hi, can you chat with another mod creator TheAnsuz - ConfigurableCompany to resolve the conflict of your mods?
https://github.com/TheAnsuz/Lethal-Company-Configurable-Company-API/issues/68

**Comment by qwbarch** [comment]
Shouldn't be an issue anymore
