### ISSUE TITLE
Can't sync mod for modpack

### ISSUE THREAD

**Issue by HighError** [qwbarch/mirage#83]
Config now saving in game folder and can't sync via modpack

- Only hear a monster mimicking your own voice while spectating
- Only record your voice while alive
- Never delete recordings

LethalConfig better LethalSettings

**Comment by qwbarch** [comment]
Working as intended as those are personal preferences and are not synced from the host to clients

**Comment by HighError** [comment]
yes, but before the last update, this setting could be saved in the mod pack so that everyone had it, but now you can’t, because the setting is saved in the folder with the game, not in the configs folder

**Comment by HighError** [comment]
Before
![image](https://github.com/user-attachments/assets/c5cd69f4-9a23-4305-a53d-190e3bb7a134)
After
![image](https://github.com/user-attachments/assets/95763d15-7311-428a-b11b-eb1cff09b29c)

**Comment by qwbarch** [comment]
Yes that's intended. I never wanted unsynced values to be in the config, since people were sharing modpacks with values like ``neverDeleteRecordings`` set to ``true``

**Comment by HighError** [comment]
I still think the setting of whether players can hear themselves should be synchronized so that the game experience is the same for everyone.

**Comment by qwbarch** [comment]
I might potentially add the two settings you mentioned back into the config, but I'll have to think about it some more

**Comment by qwbarch** [comment]
**v1.10.0** moves it back to the config
