### ISSUE TITLE
Lethal Company Mirage is "Not a valid .NET assembly"

### ISSUE THREAD

**Issue by RikkaTikka** [qwbarch/mirage#87]
The game loads via thunderstore, but despite having the mod installed with updated dependencies, when I check its settings, the mod doesn't even appear in the settings or Lethal Config. Has anyone else experienced this issue? Reinstalling the mod and dependencies didn't work, and returning to the previous version crashed my game the moment the ship loads in. I would appreciate a potential solution, if any.

The error seems to be: [Debug  :   BepInEx] Skipping loading C:\Users\(my user)\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\Mod List Update v65\BepInEx\plugins\qwbarch-Mirage\Mirage.Core.dll because it's not a valid .NET assembly. Full error: Format of the executable (.exe) or library (.dll) is invalid.
[Debug  :   BepInEx] Skipping loading C:\Users\(my user)\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\Mod List Update v65\BepInEx\plugins\qwbarch-Mirage\Mirage.dll because it's not a valid .NET assembly. Full error: Format of the executable (.exe) or library (.dll) is invalid.

**Comment by RikkaTikka** [comment]
the README and Changelog don't even have text in theme for some reason.

**Comment by qwbarch** [comment]
Sounds like something went wrong with your download if the readme and changelog are empty, as well as the dll not being able to be read properly. Try deleting and re-installing the mod maybe?

**Comment by qwbarch** [comment]
Closing the issue as it's not really a bug with Mirage. Feel free to message here still if you're still having issues.

**Comment by RikkaTikka** [comment]
I manually installed the mods, and they worked. I suspect some sort of bug kept taking place when I tried installing the mod through Thunderstore. thank you for being there to help, and thank goodness it ended up being an easy fix.
