### ISSUE TITLE
Can "LethalSettings" be changed to a soft dependency?

### ISSUE THREAD

**Issue by ajsglist** [qwbarch/mirage#88]
Running LethalSettings seems to add some significant RAM usage to the game (a few hundred MB), and we don't use it for anything.  It also seems to be rather buggy (it opens directly into the mod settings menu instead of the regular menu sometimes).  If possible, it would be great if it weren't a hard dependency so these issues could be avoided.

Cheers.

edit: RAM usage is back down to nominal levels on the last two bootups with LethalSettings, so honestly I have no idea if that's a real problem -- Lethal may have just been doing something weird.  It still has bugs opening directly into the mod settings menu instead of regular settings menu though... I wish it were maintained :(

**Comment by ajsglist** [comment]
Also saw some errors thrown at end-of-day when we left and enemies were getting despawned.  Seemed non-fatal but perhaps related to voice lines playing when the masked it getting deleted?

```
[10:30:41.8949975] [Error  : Unity Log] NullReferenceException
Stack trace:
Mirage.Domain.Audio.Receiver.onReceiveFrame (Mirage.Domain.Audio.Receiver+AudioReceiver receiver, Mirage.Domain.Audio.Frame+FrameData frameData) (at ./Mirage/Domain/Audio/Receiver.fs:61)
Mirage.Unity.AudioStream+onFrameRead@67.Invoke (Mirage.Domain.Audio.Frame+FrameData frameData) (at ./Mirage/Unity/AudioStream.fs:67)
Mirage.Domain.Audio.Sender+consumer@58-3.Invoke (Microsoft.FSharp.Core.FSharpOption`1[T] frameData) (at ./Mirage/Domain/Audio/Sender.fs:62)
Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b] (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt, b result1, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] userCode) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:528)
Microsoft.FSharp.Control.Trampoline.Execute (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] firstAction) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:112)
--- End of stack trace from previous location where exception was thrown ---
<StartupCode$FSharp-Core>.$Async+StartImmediate@1798-1.Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo edi) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:1798)
Microsoft.FSharp.Control.AsyncPrimitives+StartWithContinuations@1188-2.Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo x) (at <12b89e0ba184665de418f7f4c173580f>:IL_0000)
Microsoft.FSharp.Control.Trampoline.Execute (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] firstAction) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:138)
<StartupCode$FSharp-Core>.$Async+clo@178-14.Invoke (System.Object o) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:181)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <e27997765c1848b09d8073e5d642717a>:IL_0002)
UnityEngine.UnitySynchronizationContext.Exec () (at <e27997765c1848b09d8073e5d642717a>:IL_005D)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <e27997765c1848b09d8073e5d642717a>:IL_0014)

[10:30:41.9069986] [Error  : Unity Log] NullReferenceException
Stack trace:
Mirage.Domain.Audio.Receiver.onReceiveFrame (Mirage.Domain.Audio.Receiver+AudioReceiver receiver, Mirage.Domain.Audio.Frame+FrameData frameData) (at ./Mirage/Domain/Audio/Receiver.fs:61)
Mirage.Unity.AudioStream+onFrameRead@67.Invoke (Mirage.Domain.Audio.Frame+FrameData frameData) (at ./Mirage/Unity/AudioStream.fs:67)
Mirage.Domain.Audio.Sender+consumer@58-3.Invoke (Microsoft.FSharp.Core.FSharpOption`1[T] frameData) (at ./Mirage/Domain/Audio/Sender.fs:62)
Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b] (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt, b result1, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] userCode) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:528)
Microsoft.FSharp.Control.Trampoline.Execute (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] firstAction) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:112)
--- End of stack trace from previous location where exception was thrown ---
<StartupCode$FSharp-Core>.$Async+StartImmediate@1798-1.Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo edi) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:1798)
Microsoft.FSharp.Control.AsyncPrimitives+StartWithContinuations@1188-2.Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo x) (at <12b89e0ba184665de418f7f4c173580f>:IL_0000)
Microsoft.FSharp.Control.Trampoline.Execute (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] firstAction) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:138)
<StartupCode$FSharp-Core>.$Async+clo@178-14.Invoke (System.Object o) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:181)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <e27997765c1848b09d8073e5d642717a>:IL_0002)
UnityEngine.UnitySynchronizationContext.Exec () (at <e27997765c1848b09d8073e5d642717a>:IL_005D)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <e27997765c1848b09d8073e5d642717a>:IL_0014)
```

**Comment by qwbarch** [comment]
> Also saw some errors thrown at end-of-day when we left and enemies were getting despawned. Seemed non-fatal but perhaps related to voice lines playing when the masked is getting deleted?
> 
> ```
> [10:30:41.8949975] [Error  : Unity Log] NullReferenceException
> Stack trace:
> Mirage.Domain.Audio.Receiver.onReceiveFrame (Mirage.Domain.Audio.Receiver+AudioReceiver receiver, Mirage.Domain.Audio.Frame+FrameData frameData) (at ./Mirage/Domain/Audio/Receiver.fs:61)
> Mirage.Unity.AudioStream+onFrameRead@67.Invoke (Mirage.Domain.Audio.Frame+FrameData frameData) (at ./Mirage/Unity/AudioStream.fs:67)
> Mirage.Domain.Audio.Sender+consumer@58-3.Invoke (Microsoft.FSharp.Core.FSharpOption`1[T] frameData) (at ./Mirage/Domain/Audio/Sender.fs:62)
> Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b] (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt, b result1, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] userCode) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:528)
> Microsoft.FSharp.Control.Trampoline.Execute (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] firstAction) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:112)
> --- End of stack trace from previous location where exception was thrown ---
> <StartupCode$FSharp-Core>.$Async+StartImmediate@1798-1.Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo edi) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:1798)
> Microsoft.FSharp.Control.AsyncPrimitives+StartWithContinuations@1188-2.Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo x) (at <12b89e0ba184665de418f7f4c173580f>:IL_0000)
> Microsoft.FSharp.Control.Trampoline.Execute (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] firstAction) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:138)
> <StartupCode$FSharp-Core>.$Async+clo@178-14.Invoke (System.Object o) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:181)
> UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <e27997765c1848b09d8073e5d642717a>:IL_0002)
> UnityEngine.UnitySynchronizationContext.Exec () (at <e27997765c1848b09d8073e5d642717a>:IL_005D)
> UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <e27997765c1848b09d8073e5d642717a>:IL_0014)
> 
> [10:30:41.9069986] [Error  : Unity Log] NullReferenceException
> Stack trace:
> Mirage.Domain.Audio.Receiver.onReceiveFrame (Mirage.Domain.Audio.Receiver+AudioReceiver receiver, Mirage.Domain.Audio.Frame+FrameData frameData) (at ./Mirage/Domain/Audio/Receiver.fs:61)
> Mirage.Unity.AudioStream+onFrameRead@67.Invoke (Mirage.Domain.Audio.Frame+FrameData frameData) (at ./Mirage/Unity/AudioStream.fs:67)
> Mirage.Domain.Audio.Sender+consumer@58-3.Invoke (Microsoft.FSharp.Core.FSharpOption`1[T] frameData) (at ./Mirage/Domain/Audio/Sender.fs:62)
> Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b] (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt, b result1, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] userCode) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:528)
> Microsoft.FSharp.Control.Trampoline.Execute (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] firstAction) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:112)
> --- End of stack trace from previous location where exception was thrown ---
> <StartupCode$FSharp-Core>.$Async+StartImmediate@1798-1.Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo edi) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:1798)
> Microsoft.FSharp.Control.AsyncPrimitives+StartWithContinuations@1188-2.Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo x) (at <12b89e0ba184665de418f7f4c173580f>:IL_0000)
> Microsoft.FSharp.Control.Trampoline.Execute (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] firstAction) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:138)
> <StartupCode$FSharp-Core>.$Async+clo@178-14.Invoke (System.Object o) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:181)
> UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <e27997765c1848b09d8073e5d642717a>:IL_0002)
> UnityEngine.UnitySynchronizationContext.Exec () (at <e27997765c1848b09d8073e5d642717a>:IL_005D)
> UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <e27997765c1848b09d8073e5d642717a>:IL_0014)
> ```

Thanks for the report, I must've missed some safety checks while rewriting it. If it's harmless I'm probably not going to touch it for now, since I'm busy with other things.

To answer your first question: LethalSettings is used because there's no better alternative for what I'm trying to do. Basically, I needed an interface for personal preferences (values that shouldn't be synced), and when it was defined in the config, a personal pain point for me was having to change the personal preferences every time I imported someone else's modpack.
With LethalSettings, I can define my own non-synced data, and every time I import someone else's modpack, I still have my own preferences set.

I'll be closing the issue, but if you have any other concerns, feel free to ask.
