### ISSUE TITLE
Cannot tweak Mirage settings anymore through LethalConfig (v1.10.0)

### ISSUE THREAD

**Issue by Amaalecule** [qwbarch/mirage#89]
Pardon my technical illiteracy, but I cannot find or modify any settings for Mirage following the recent v1.10.0 patch. Instead, it **only** allows modification of voice volume and whether recordings are deleted, and this is through the settings tab when it was once under LethalConfig. I am unsure how to tweak spawn rates or voice line frequency as a result and wanted to know if there is any possibility of configuring the mod further perhaps through the game files or something.

Unsure why the change happened, but I'm nowhere near competent enough to find out how to resolve it. Hope I was able to competently describe the issue; let me know if you'd like any further details and I'll try my best :)

**Comment by qwbarch** [comment]
Does nothing show up when you search for ``Mirage`` in the mod manager's config editor? ``LethalSettings`` is only for the local preferences, the config is still separate

**Comment by ReikoRei** [comment]
my bad
![image](https://github.com/user-attachments/assets/eba00209-d51c-4985-aa5b-5301cb8c37df)
I usually configure mods via LethalSetting
I didn't notice that I can configure mods directly in the mod manager

**Comment by Amaalecule** [comment]
got it. I didn't realize I could edit the config via the mod manager either, so thank you for the help :)

**Comment by Strat00s** [comment]
for me, the config does not generate no matter how many times I run it.
![image](https://github.com/user-attachments/assets/508ee830-127b-4baf-8eaf-58fe78ba4350)

**Comment by qwbarch** [comment]
> for me, the config does not generate no matter how many times I run it. ![image](https://private-user-images.githubusercontent.com/24775036/373955033-508ee830-127b-4baf-8eaf-58fe78ba4350.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjM4MDYsIm5iZiI6MTcyODI2MzUwNiwicGF0aCI6Ii8yNDc3NTAzNi8zNzM5NTUwMzMtNTA4ZWU4MzAtMTI3Yi00YmFmLThlYWYtNThmZTc4YmE0MzUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDAxMTE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZjAwZWE3ZjRmZWJkZjhkNGI3ZGQ2NjdjZmQwZjkyNzFiYmY4MWEyODJjNjU3NTk5YjdmN2ZmN2RkODM1MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QoQBHyutax4gRkWxZT8zXuMBcWq4ep2JDXyp1-u95iU)

Can you send your logs? If the config is not being generated, it's probably due to errors on startup for whatever reason
