### ISSUE TITLE
Voice Recordings only created from Hostvoice

### ISSUE THREAD

**Issue by Yasaka7** [qwbarch/mirage#91]
So i host a Lethal Company Session sometimes, we switched from Skinwalker to this since Skinwalker stopped working entirely for some reason, but we have the problem that the voicelines are only recorded from my voice. All other players can hear it but voicelines from other players except me(as host) are never created. 
We use MaskedEnemyOverhaulFork with the "Dont Touch MaskedPlayerEnemy.mimickingPlayer" on true. We share the same modpack with the same config through R2modman. we also checked that all our config files are identical.
Any ideas?

**Comment by DenBelkov** [comment]
Same thing for me except it's not even me (the host) who gets recorded. Throughout like 3 hours of me playing with my friends we could only hear recordings of one of said friends of mine.

**Comment by qwbarch** [comment]
Could you guys upload a log? I imagine there'd be a lot of errors if
there's an issue like this

**Comment by DenBelkov** [comment]
[LogOutput.log](https://github.com/user-attachments/files/17285833/LogOutput.log)

**Comment by qwbarch** [comment]
@DenBelkov Thanks, I think it was related to something I was trying to fix. Could you try running with [MirageExperimental](<https://thunderstore.io/c/lethal-company/p/qwbarch/MirageExperimental/>) and see if it's fixed? Specifically version ``0.0.34``.

**Comment by qwbarch** [comment]
Should be fixed in the latest update. If the issue still occurs, feel free to re-open the issue
