### ISSUE TITLE
lethal company mirage mod. friends and i cannot hear mimicked voices

### ISSUE THREAD

**Issue by bruvahh** [qwbarch/mirage#92]
we can hear other modded audios from monsters but not mimicked voices of ours. the masked enemy configs are working where they act more like players and higher spawn rate but no voices. the code to our modpack is "01926a44-b312-6991-823d-9d900da2271b" if you might need it. the in game setting for voice audio is at 100% and the configs are configured so we get voice lines frequently and all dependencies installed and our configs match so idk what the issue might be any help is appreciated

**Comment by qwbarch** [comment]
Should be fixed in the latest update. If the issue still occurs, feel free to re-open the issue
