### ISSUE TITLE
syncedConfig has not been initialized yet.

### ISSUE THREAD

**Issue by MattWojo73** [qwbarch/mirage#93]
Hello, I have keep getting this error in the BepInEx console anytime I start land on a planet. I'm not sure if I installed something incorrectly, or what is going on exactly. Mimics are still able to walk around, but I'm not sure if they're playing voice lines or not.

This is the error ~

[Error  :qwbarch.Mirage] syncedConfig has not been initialized yet.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Mirage.Domain.Config.getConfig () (at ./Mirage/Domain/Config.fs:193)
Mirage.Unity.MimicPlayer+MimicPlayer.StartMimicking () (at ./Mirage/Unity/MimicPlayer.fs:66)
Mirage.Unity.MimicPlayer+MimicPlayer.Start () (at ./Mirage/Unity/MimicPlayer.fs:56)

[Error  :qwbarch.Mirage] syncedConfig has not been initialized yet.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Mirage.Domain.Config.getConfig () (at ./Mirage/Domain/Config.fs:193)
Mirage.Unity.MirageVoice+clo@43-13.Invoke (Microsoft.FSharp.Core.Unit unitVar) (at ./Mirage/Unity/MimicVoice.fs:47)
Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult] (Microsoft.FSharp.Control.AsyncActivation`1[T] ctxt, TResult result1, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] part2) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:510)
Microsoft.FSharp.Control.Trampoline.Execute (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] firstAction) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:112)
--- End of stack trace from previous location where exception was thrown ---
<StartupCode$FSharp-Core>.$Async+StartImmediate@1798-1.Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo edi) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:1798)
Microsoft.FSharp.Control.AsyncPrimitives+StartWithContinuations@1188-2.Invoke (System.Runtime.ExceptionServices.ExceptionDispatchInfo x) (at <12b89e0ba184665de418f7f4c173580f>:IL_0000)
Microsoft.FSharp.Control.Trampoline.Execute (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] firstAction) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:138)
Microsoft.FSharp.Control.AsyncPrimitives.StartWithContinuations[T] (System.Threading.CancellationToken cancellationToken, Microsoft.FSharp.Control.FSharpAsync`1[T] computation, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] cont, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] econt, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] ccont) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:1182)
Microsoft.FSharp.Control.FSharpAsync.StartImmediate (Microsoft.FSharp.Control.FSharpAsync`1[T] computation, Microsoft.FSharp.Core.FSharpOption`1[T] cancellationToken) (at D:/a/_work/1/s/src/FSharp.Core/async.fs:1798)
Mirage.Unity.MirageVoice+MimicVoice.startVoiceMimic () (at ./Mirage/Unity/MimicVoice.fs:52)
Mirage.Unity.MirageVoice+MimicVoice.Start () (at ./Mirage/Unity/MimicVoice.fs:72)

**Comment by MattWojo73** [comment]
It doesn't seem to be affecting the mimics or the voice lines, I just did a test with multiple people and everything was working fine, the error still gets thrown tho

**Comment by qwbarch** [comment]
Does this happen with only Mirage installed? It sounds like another mod is disabling the patch that Mirage uses to initialize the config

**Comment by qwbarch** [comment]
Closing this issue as there hasn't been a response in awhile. Feel free to re-open if you're here.
